Feat/sideinput source sinks
numaproj-contrib/e2e-tests-go pull request #2
Opened 2023-10-25 03:06 UTC by shubhamdixit863

Modified side input ,source and sinks for e2e tests ,for testing sideinput e2e tests

2023-10-26 14:07 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaproj-contrib/e2e-reduce-sideinput-udf:$(basename $GITHUB_REF)"
this two line change is not required, i think think this changes came while resolving conflict.

2023-10-26 14:45 UTC, chandankumar4 requested changes
nit:
1. I think we need to follow same directory naming convention, probably with `-` as separator. we have used the mixed of `-` and `_`
2. Need to add README file in `sideinput_function`

Sorry for putting so many review comment but most of them are just nit pick.

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaproj-contrib/e2e-reduce-sideinput-udf:$(basename $GITHUB_REF)"
this two line change is not required, i think this changes came while resolving conflict.

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
this step is not required as it's already done on next step

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          TAG: $(basename $GITHUB_REF)
```suggestion
          TAG: ${{ env.IMAGE_TAG }}
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
```suggestion
        if: startsWith(github.ref, 'refs/tags/v')
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaflow-sink/redis-e2e-test-sink-with-sideinput:$(basename $GITHUB_REF)"
```suggestion
          docker push "quay.io/numaio/numaflow-sink/redis-e2e-test-sink-with-sideinput:${{ env.IMAGE_TAG }}"
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
this steps is not require

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          TAG: $(basename $GITHUB_REF)
```suggestion
          TAG: ${{ env.IMAGE_TAG }}
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
```suggestion
        if: startsWith(github.ref, 'refs/tags/v')
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaflow-source/simple_source_with_sideinpu:$(basename $GITHUB_REF)"
```suggestion
          docker push "quay.io/numaio/numaflow-source/simple_source_with_sideinpu:${{ env.IMAGE_TAG }}" 
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +
this step is not require

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          TAG: $(basename $GITHUB_REF)
```suggestion
          TAG: ${{ env.IMAGE_TAG }}
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
```suggestion
        if: startsWith(github.ref, 'refs/tags/v')
```

2023-10-26 14:45 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaflow-sideinput/sideinput-sink-e2e-test:$(basename $GITHUB_REF)"
```suggestion
          docker push "quay.io/numaio/numaflow-sideinput/sideinput-sink-e2e-test:${{ env.IMAGE_TAG }}"          
```

2023-10-26 14:45 UTC, chandankumar4 commented on sideInput_function/Makefile
> +	docker buildx build --no-cache -t "$(DOCKERIO_ORG)/numaflow-sideinput/sideinput-sink-e2e-test:$(IMAGE_TAG)" --platform $(PLATFORM) --target $(TARGET) . --load
```suggestion
	docker buildx build --no-cache -t "$(DOCKERIO_ORG)/numaproj-contrib/sideinput-sink-e2e-test:$(IMAGE_TAG)" --platform $(PLATFORM) --target $(TARGET) . --load
```

2023-10-26 14:45 UTC, chandankumar4 commented on sideInput_function/Makefile
> +	docker buildx build --no-cache -t "$(DOCKERIO_ORG)/numaflow-sideinput/sideinput-sink-e2e-test:$(IMAGE_TAG)" --platform $(PLATFORM) --target $(TARGET) . --load
we can put `numaflow-sideinput` as well but just following it with repo name, similar to other existing approach in other places :)

2023-10-26 14:45 UTC, chandankumar4 commented on sideInput_function/dist/sideinput-example
I don't think we need to publish binary file

2023-10-26 14:45 UTC, chandankumar4 commented on sideInput_function/main.go
> +	"log"
nit:
probably a re-arrange is required, I think go-import should fix it.

```
        "context"
	"log"

	sideinputsdk "github.com/numaproj/numaflow-go/pkg/sideinput"

```

2023-10-26 14:45 UTC, chandankumar4 commented on sideInput_function/main.go
> +	// NoBroadcastMessage() is used to drop the message and not to
nit:
probably need to update the comment here, as we are not dropping any message here.

2023-10-26 14:45 UTC, chandankumar4 commented on simple_source_with_sideinput/go.mod
> +go 1.20
It will be good if we keep same version everywhere, I think above I have seen as 1.21

2023-10-26 14:45 UTC, chandankumar4 commented on simple_source_with_sideinput/dist/simple-source-example
nit:
Need to remove this file from commit

2023-10-26 14:45 UTC, chandankumar4 commented on simple_source_with_sideinput/impl/simple_source_sideinput.go
> +			log.Println("Value received in global chan444444--------", value)
nit:
I think this was for debugging?

2023-10-26 14:45 UTC, chandankumar4 commented on simple_source_with_sideinput/impl/simple_source_sideinput.go
> +				log.Println("File contents Original-- :----------------------- ", string(b))
nit:
Is this log required? then probably need to update message.

2023-10-26 14:45 UTC, chandankumar4 commented on sink-side-input/go.mod
> +go 1.18
```suggestion
go 1.21
```

2023-10-26 14:45 UTC, chandankumar4 commented on sink-side-input/go.mod
> +module github.com/numaproj/numaflow-sinks/argoworkflow
nit:
Need to update the path

2023-10-26 14:45 UTC, chandankumar4 commented on sink-side-input/main.go
> +	sinksdk "github.com/numaproj/numaflow-go/pkg/sinker"
nit:
need to run go-import here

2023-10-26 14:45 UTC, chandankumar4 commented on sink-side-input/main.go
> +		log.Printf(" %s Side input content----", content)
was this logs for debugging?

2023-10-26 14:45 UTC, chandankumar4 commented on sink-side-input/main.go
> +				log.Println("File contents Original-- :----------------------- ", string(b))
nit:
Is it required? or it was for debugging?

2023-10-26 17:46 UTC, shubhamdixit863 commented on sideInput_function/Makefile
> +	docker buildx build --no-cache -t "$(DOCKERIO_ORG)/numaflow-sideinput/sideinput-sink-e2e-test:$(IMAGE_TAG)" --platform $(PLATFORM) --target $(TARGET) . --load
I am following the quay.io norms they are putting all the sinks under numaflow-sink and likewise

2023-10-26 21:17 UTC, KeranYang commented on simple-source-with-sideinput/impl/simple_source_sideinput_test.go
> +		// Read 2 messages
```suggestion
```

2023-10-26 21:17 UTC, KeranYang commented on sink-side-input/README.md
> +This sink is used by E2E testing.
please update the description. 1. we now set side input content as key in redis instead of the message payload and 2. the value is the no. of occurrence of the key instead of 1.(I [updated](https://github.com/numaproj/numaflow-sinks/pull/29/files) in the original redis sink)

2023-10-27 03:40 UTC, chandankumar4 requested changes

2023-10-27 03:40 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        uses: actions/checkout@v3
this two steps need to interchange as step1 won't work without step2
Also add below changes for action/checkout
```
        with:
          fetch-depth: '0'
```

2023-10-27 03:40 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +          TAG: $(env.IMAGE_TAG)
```suggestion
          TAG: ${{env.IMAGE_TAG }}
```

2023-10-27 03:40 UTC, chandankumar4 commented on .github/workflows/ci.yaml
> +        uses: actions/checkout@v3
need to interchange the steps here also. and add `fetch-depth: 0` in checkout

2023-10-27 03:40 UTC, chandankumar4 commented on sideInput-function/go.mod
> +module github.com/numaproj/numaflow-sinks/argoworkflow
should it be argoworkflow ?

2023-10-27 03:40 UTC, chandankumar4 commented on simple-source-with-sideinput/go.mod
> +module github.com/numaproj/numaflow-go/pkg/sourcer/examples/simple_source
I think it need to be updated, looks like copied from numaflow-go example

2023-10-27 10:34 UTC, shubhamdixit863 commented on .github/workflows/ci.yaml
> +          docker push "quay.io/numaio/numaproj-contrib/e2e-reduce-sideinput-udf:$(basename $GITHUB_REF)"
@chandankumar4 can you confirm this to be removed now ,as its pushing the image to quay.io

2023-10-27 11:16 UTC, chandankumar4 approved these changes
LGTM

2023-10-27 14:44 UTC, KeranYang approved these changes

2023-10-27 14:46 UTC, merged

2023-10-27 14:48 UTC, KeranYang commented
LGTM. Thanks for making the change @shubhamdixit863 , I merged it.